apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-olympus-secrets
  labels:
    {{- include "olympus.labels" . | nindent 4 }}
type: Opaque
stringData:
  THEMIS_JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgres.password | quote }}
  MINIO_ACCESS_KEY: {{ .Values.global.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.global.minio.secretKey | quote }}