apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "console.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "console.saName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            {{- $root := . }}
            {{- range $svc, $port := .Values.servicePorts }}
            - name: {{ $svc | upper }}_URL
              value: {{ printf "http://%s-%s:%v" $root.Release.Name $svc $port | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}