apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "console.selectorLabels" . | nindent 4 }}