{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "olympus.fullname" . }}-gateway
  labels:
    {{- include "olympus.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "olympus.selectorLabels" . | nindent 6 }}
      component: gateway
{{- end }}