apiVersion: v1
kind: Secret
metadata:
  name: {{ include "olympus.fullname" . }}-secret
  labels:
    {{- include "olympus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.existingSecret }}
  {{- else }}
  POSTGRES_DSN: {{ printf "host=%s port=%d user=%s password=%s dbname=%s sslmode=disable" .Values.postgresql.host (.Values.postgresql.port | int) .Values.postgresql.user .Values.postgresql.password .Values.postgresql.dbname | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
  {{- else }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | default "" | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | default "" | quote }}
  {{- end }}