package pkg

import (
	"context"
	"database/sql"
	"errors"
)

// Instance and snapshot states managed by the provisioner and persisted in Postgres.
const (
	StatePending  = "pending"
	StateCreating = "creating"
	StateActive   = "active"
	StateUpdating = "updating"
	StateStopping = "stopping"
	StateStopped  = "stopped"
	StateStarting = "starting"
	StateDeleting = "deleting"
	StateDeleted  = "deleted"
)

// ErrNotFound is returned when a requested project or resource does not exist.
var ErrNotFound = errors.New("not found")

// ErrConflict is returned when an operation cannot transition from the current state.
var ErrConflict = errors.New("state conflict")

// IsNotFound reports whether an error is ErrNotFound (incl. wrapped sql.ErrNoRows).
func IsNotFound(err error) bool {
	return err == ErrNotFound || err == sql.ErrNoRows
}

// InstanceSpec describes everything needed to provision a managed database instance.
type InstanceSpec struct {
	ID                 string
	ProjectID          string
	Name               string
	Engine             string
	EngineVersion      string
	Size               string
	AllocatedStorageGB int
	MasterUsername     string
	// MasterPassword is generated by the control plane and handed to the
	// provisioner once, so the backend can grant real access.
	MasterPassword string
}

// InstanceCreds holds the connection material a managed instance exposes.
type InstanceCreds struct {
	ProviderRef    string
	Endpoint       string
	MasterUsername string
	MasterPassword string
}

// SnapshotSpec describes a point-in-time copy of a managed instance.
type SnapshotSpec struct {
	InstanceRef string
	InstanceID  string
	ProjectID   string
	Name        string
	Engine      string
	Size        int
}

// ProvisionedSnapshot is the provider-side reference for a snapshot.
type ProvisionedSnapshot struct {
	ProviderRef string
	SizeGB      int
}

// Provisioner is the pluggable "data plane" behind the Clio control plane.
// A mock implementation ships with Clio; a real backend (e.g. a fleet of
// PostgreSQL containers, Aurora/RDS, or a home-grown engine) can implement the
// same interface.
type Provisioner interface {
	// CreateInstance provisions a real database engine and returns where to
	// reach it plus the credentials the control plane generated.
	CreateInstance(ctx context.Context, spec InstanceSpec) (*InstanceCreds, error)
	// DeleteInstance tears a database instance down for good.
	DeleteInstance(ctx context.Context, providerRef string) error
	// StartInstance resumes a stopped instance.
	StartInstance(ctx context.Context, providerRef string) error
	// StopInstance pauses a running instance.
	StopInstance(ctx context.Context, providerRef string) error
	// CreateSnapshot produces a point-in-time copy of a managed instance.
	CreateSnapshot(ctx context.Context, spec SnapshotSpec) (*ProvisionedSnapshot, error)
	// DeleteSnapshot removes a stored snapshot.
	DeleteSnapshot(ctx context.Context, providerRef string) error
	// Healthy reports whether the data plane is reachable.
	Healthy(ctx context.Context) error
}
