image:
  repository: olympus/paramdora
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
port: 8083
dbname: olympus_parameters
env:
  - name: KEY_ENC_MASTER
    value: ""
serviceAccount:
  create: true
  name: ""
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi