apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "olympus.fullname" . }}-gateway
  labels:
    {{- include "olympus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "olympus.selectorLabels" . | nindent 6 }}
      component: gateway
  template:
    metadata:
      labels:
        {{- include "olympus.selectorLabels" . | nindent 8 }}
        component: gateway
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "olympus.fullname" . | quote }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      terminationGracePeriodSeconds: 30
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "olympus.fullname" . }}-config
            - secretRef:
                name: {{ include "olympus.fullname" . }}-secret
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}